name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: '*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
    quality:
        runs-on: ${{matrix.os}}

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]
                os: [ubuntu-latest, windows-latest]

        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with: 
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
          - run: npm ci
        #   - run: npm test
    
    publish:
        runs-on: ubuntu-latest
        if: ${{github.ref == 'refs/heads/main'}}
        needs: [quality]
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@v4
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}